### ISSUE TITLE
v1.1 is not semantically distinct from v1

### ISSUE THREAD

**Issue by ekg** [GFA-spec/GFA-spec#109]
Other than asserting that there is some new way of representing approximate haplotypes, is there a reason to update the version number? The methods which support v1 do so with limitations. They don't all support all the field types. So why add v1.1 to distinguish one new field type?

**Comment by ggonnella** [comment]
Most existing implementations probably do not handle yet the W lines - and since GFA1 does not require to ignore lines starting with a different record type code than those mentioned in the specification,
stricly speaking, GFA v1.1 containing W lines is not valid GFA v1.
So I think giving a hint of their possible presence in the file through a higher minor version number can be useful.

**Comment by ekg** [comment]
Well that's a good point. The spec doesn't say "you must ignore lines you don't use." Practically, tools do ignore lines that they don't use. Seems fine to increment, if confusing given that the W and P lines are mutually redundant.
