### ISSUE TITLE
Circular paths

### ISSUE THREAD

**Issue by rrwick** [GFA-spec/GFA-spec#23]
I'm working on adding GFA path support to Bandage, and I'm wondering how to deal with the concept of circular paths.  In bacterial genomics, the actual DNA is usually circular, so important graph paths (e.g. a plasmid sequence in an assembly graph) will also be circular.  As I see it, the difference between a linear and a circular path is whether the overlap between the first and last node is considered.

So I propose that in a linear path:
- The segment list does not end in a comma.
- The list of CIGAR strings has one fewer part than the segment list.

In a circular path:
- The segment list ends in a comma (to indicate the link between last and first segments).
- The list of CIGAR strings has the same number of parts as the segment list.

Here's an example GFA to illustrate:

```
H   VN:Z:1.0
S   1   AGCGTA
S   2   TAACAG
L   1   +   2   +   2M
L   2   +   1   +   2M
P   linear  1+,2+   2M
P   circular    1+,2+,  2M,2M
```

So in this example, the linear path would have this sequence:
`AGCGTAACAG`

And the circular path would have this sequence:
`AGCGTAAC`

Thoughts?

**Comment by ekg** [comment]
All that needs to be done to support circular paths is to indicate the path
rank of the particular "mapping" to a given node. Then you can have as many
loops over a given node as you need. VG implements this. I'll reply with an
example.

**Comment by sjackman** [comment]
Hmm. Interesting question, Ryan. I don't like the cryptic use of the bare terminal comma to indicate that the path is circular. I'd prefer an explicit optional tag to indicate that it's circular. Something like
```
P circular 1+,2+,1+ 2M,2M Z:FL:circular
P circular 3+,3+ 2M Z:FL:circular
```
where FL stands for flag. Another option for the tag would be `i:CI:1`, where CI stands for circular.

**Comment by ekg** [comment]
If we add ranks to path elements, we don't need to enumerate the entire path on one line and we also get around the issue of circular paths by making it self-evident from the data what's cyclic and what's not.

Here is an example:

![screenshot from 2015-12-20 20 01 51](https://cloud.githubusercontent.com/assets/145425/11921330/cc97674c-a754-11e5-9871-2ef715ea640a.png)

GFA (not to spec, but I'm proposing we follow something like this):

```text
H       HVN:Z:1.0
S       1       TC
P       1       s1      1       +       2M
P       1       s2      1       +       2M
L       1       +       2       +       0M
S       2       AGATTCTCATCCCTCCTCAAGGGCTTCT
P       2       s1      2       +       28M
P       2       s2      2       +       28M
P       2       s3      6       +       28M
P       2       s3      13      +       28M
L       2       +       6       +       0M
L       2       +       3       +       0M
S       3       AACTACT
P       3       s1      3       +       7M
P       3       s3      7       +       7M
L       3       +       4       +       0M
S       4       CCACATCAAAGCTACCCAG
P       4       s1      4       +       19M
P       4       s3      1       +       19M
P       4       s3      8       +       19M
L       4       +       5       +       0M
S       5       GCCATTTTAAGTTTCCTGT
P       5       s1      5       +       19M
P       5       s3      2       +       19M
L       5       +       6       +       0M
S       6       GGACTAA
P       6       s1      6       +       7M
P       6       s2      3       +       7M
P       6       s3      3       +       7M
P       6       s3      10      +       7M
P       6       s3      14      +       7M
L       6       +       7       +       0M
S       7       GGACAAAGGT
P       7       s1      7       +       10M
P       7       s2      4       +       10M
P       7       s3      4       +       10M
P       7       s3      11      +       10M
L       7       +       8       +       0M
L       7       +       10      +       0M
S       8       GCGGGGAG
P       8       s1      8       +       8M
P       8       s2      5       +       8M
S       10      GCGGGGAGTC
P       10      s3      5       +       10M
P       10      s3      12      +       10M
L       10      +       2       +       0M
```

(If I'm misunderstanding please steer me right!)

**Comment by rrwick** [comment]
Erik,

Your example splits a path onto many lines, each showing the position of a node in the path, but I'm not seeing how this is different in principle from how GFA paths currently work.  Wouldn't it be equivalent to show the paths in your graph like this:
```
P	s1	1+,2+,3+,4+,5+,6+,7+,8+	0M,0M,0M,0M,0M,0M,0M
P	s2	1+,2+,6+,7+,8+	0M,0M,0M,0M
P	s3	4+,5+,6+,7+,9+,2+,3+,4+,5+,6+,7+,10+,2+,6+	0M,0M,0M,0M,0M,0M,0M,0M,0M,0M,0M,0M,0M
```

Also, I don't see how this makes circular paths evident.  For example, what if there was a circular path in your graph that followed `4+,5+,6+,7+,9+,2+,3+` and then seamlessly connected back to its starting node of 4+?  How could it show that?  To be clear, when I say 'circular paths', I'm not referring to paths which contain loops, but rather cases where the entire path is one big loop.

Ryan

**Comment by rrwick** [comment]
Shaun,

A tag would work to distinguish circularity, and I'm not fussed over the two options you presented.  I'd be happy to go with whichever you prefer.

But the other difference between my examples and yours seems to be whether the path starts and ends with the same segment.

I find this misleading, as it suggests that segment 1+ is present in the path twice:
`P circular1 1+,2+,1+ 2M,2M Z:FL:circular`

Could we instead have it look like this:
`P circular1 1+,2+ 2M,2M Z:FL:circular`

This would still entail what I stated in my first post, which is that a circular path has a CIGAR list of equal length to the segment list, while a linear path has one fewer CIGAR string.

Ryan

**Comment by ekg** [comment]
Adding the rank to the record allows us to have several mappings with the
same path to the same node and unambiguously tell where the node is in the
path. We don't need to record the entire path on one line this way, and we
can extract valid subsets of the graph without needing to transmit the
entire path (which in cases I am working on is hundreds of megabases).

**Comment by rrwick** [comment]
Erik,

I see the advantage of being able to extract part of a path from part of a large graph file.  Though I'm a bit confused... looking back at the GFA discussions around paths, didn't you suggest [here](https://github.com/pmelsted/GFA-spec/issues/22) that it's better to put paths on a single line?

And apologies if I'm being dense and missing something, but I still don't see how this relates to the issue of identifying circular paths.

Ryan

**Comment by sjackman** [comment]
Hi, Ryan. I'm okay with your suggestion that a circular path have the same number of segments as cigar strings. In that case, you don't necessarily need an explicit overlap tag either.

**Comment by sjackman** [comment]
I prefer to keep the path on a single line rather than break it over multiple lines. I haven't thought of how to take a subset of a graph that includes only some of the vertices of a path, particularly if that path weaves into and out of that subset a few times.

**Comment by ekg** [comment]
Ryan,

I did but in practice this is extremely difficult to work with due to the
problems I mentioned. If each path needs to be fully represented each time
it is mentioned then there can be no subsets of the graph that are still
valid in their representation. By adding ranks to the path memberships we
get away from this issue. This is what I have implemented and I don't see
any way I can change if unless we make GFA even more complicated.

I guess it isn't necessary for circular paths because we can enumerate the
entire path as I suggested before. But, the ranks do make it easier to
check when there is a cycle. You would find the same node to have multiple
path records for a given path. This is simpler than loading and traversing
the entire path.

But! this doesn't solve the problem we need to fix for circular chromosomes
because we have no way of specifying when the ending and starting mappings
in the path are connected as well. So, I'm sorry for the noise about this.
It is a bit off-topic, but paths hadn't come up in discussion in a while.

I do wish there was a way to do this that wasn't based on a keyword. Why
not add a start and end marker to each path? If the path has neither then
it is circular. This would also explicitly communicate the start and end
and could allow the description of subsets of the graph.

Erik

**Comment by rrwick** [comment]
I don't know... I kind of like the keyword as it makes it more human readable.  Of the two options Shaun proposed, I'm leaning towards `Z:FL:circular` for that reason - a person looking at the file is more likely to understand what's going on.

However, I also like your mention of start/end markers, though I feel that's a different enough topic to deserver a separate thread.  I'll start one now!

**Comment by rrwick** [comment]
So to summarise, I'll tentatively go ahead with the following for circular paths:
* The number of CIGAR strings is equal to the number of segments (because there is an additional link from the last segment back to the first)
* This tag is used to explicitly state that the path is circular: `Z:FL:circular`

**Comment by sjackman** [comment]
Works for me, Ryan. Please open a pull request to propose the modifications to the spec. Should Z:FL be a comma separated list of text flags? That's not unfortunately a very compact representation, but circular paths aren't usually terribly common in great numbers.

**Comment by ekg** [comment]
Is there any other feature of the graph that requires a keyword or tag to represent?

Until this point (and assuming paths can be represented with one node mapping per line) I have been able to read and write entire graphs with an extremely simple parser. Keywords complicate this. In VCF we don't need any keywords to represent the underlying sequence DAG. By extending path semantics as I have proposed we can avoid the need for a keyword.

Circular paths will be very common in any representation of a collection of bacterial sequences. We should do this cleanly.

**Comment by sjackman** [comment]
Erik, I have similar reservations about adding text keywords. We don't need the keyword. The circular path is represented by the number of segments being equal to the number of cigar operations. Ryan, if you want to make it more explicit and human readable, you could add "circular" to a comment at the end of the line. Are `#` allowed at the end of a line or just the beginning? Perhaps instead `Z:CO:circular` and it is purely a comment.

**Comment by rrwick** [comment]
Okay, I can drop the flag and make the CIGAR list the sole defining feature of circular paths.

I just need to clarify one thing: If you are using * in place of CIGAR strings, must you use a separate * for each CIGAR string in the list?  Or are you allowed to use a single * in place of the whole list?

Here's an example:
```
H	VN:Z:1.0
S	1	AGCGTA
S	2	TAACAG
S	3	GTCATC
L	1	+	2	+	2M
L	2	+	3	+	2M
L	3	+	1	+	2M
P	linear_path	1+,2+,3+	*,*
P	circular_path	1+,2+,3+	*,*,*
P   is_this_okay   1+,2+,3+    *
```

The last path, 'is_this_okay', uses a single * for the whole CIGAR list.  Is this an invalid GFA path?  If it is allowed, then do we assume a non-circular path in such a case?

**Comment by sjackman** [comment]
Good question. My inclination would be to use a single asterisk to omit all the cigar strings. I suppose you could use an asterisk to omit just one cigar string. It makes sense. I just hadn't thought of it. I would say `is_this_okay` is okay and is a linear path. The other two paths are also okay.

**Comment by ekg** [comment]
Now I'm confused. Without an indication of where a path starts and stops, how can we determine if it's circular? Won't we need a keyword then?

I'm really regretting proposing the single-line path. It breaks the single-line tabular semantics that make GFA simple to read and parse. If we can record the ranks of elements in the path, is there any reason to make paths special in their representation?

**Comment by sjackman** [comment]
A path is circular if the number of segments equals the number of cigar strings. The cigar strings may all be asterisks if the exact cigar string is unknown.

**Comment by sjackman** [comment]
I prefer the single line record format because it's a simpler more compact format for the common case (at least for me). The biggest downside in my opinion is that it makes taking a subset of a graph including paths more difficult.

**Comment by ekg** [comment]
The one line for each path has these drawbacks.

1. No way to subset the graph or combine subsets of the graph without
additional semantics to describe how paths are subset.
2. Introduces a sub-format for a fundamental component of the graph.
3. Prevents the use of streaming command-line tools for inspecting the
paths of the graph.
4. Prevents using bgzip to index GFA files and extract subgraphs based on
node ranges or other kinds of sorting.

With a slight, but non-redundant increase in verbosity we can solve all of
these issues. As far as I understand, the path format I am proposing has no
drawbacks aside from verbosity, most of which is repeating the path name. I
don't see this as a serious issue as it doesn't impact on-disk size
substantially provided we compress GFA using bgzip.

It also sets us up for a mechanism to define if a path is circular or not.
The way to do this is to describe where a path starts and ends. If it does
not have a start or end then it should be circular (or it could be invalid,
or a subset of the path). We could do this by adding only two special
cases. The path start on the positive strand could be #+, on the negative
#-, and for the end +$ or -$.

**Comment by sjackman** [comment]
There are certainly advantages to a multilingual path format, as you describe above. I'm concerned that the existing path format has been around long enough that there are likely existing implementations, and I'd prefer not to break compatibility with those implementations by redefining the `P` record. Would you like to propose a new record format in a separate issue?

I don't think that a leading sentinel is necessary, since the first segment of the path has rank 1, but a terminal sentinel may be necessary to tell the parser that the path is complete and no more records are expected for that path. The biggest downside to a multiline path record is that it splits the definition of a single element, a path, over multiple lines.

**Comment by pmelsted** [comment]
Reviving this debate again.

I must agree with @sjackman that in my opinion multiline representations of objects are not good. They make it harder to write a parser where we don't know if a path has been closed or not. The convention that a single object (segment, link or path) be on a single line makes parsing easier.

On the other hand finding a subgraph requires you to parse the one line representation of the path and then subset the adjacent segments in the paths. I agree that this is easier where each link on the path is on a separate line, thus making it easier to parse via unixy tools or a simpler parser.

However we need to think a bit about semantics. What does it mean that we specify a path element P? It means that we have evidence that the segments listed in the path occur in the some fragment.

Copying from @rrwick 's example above

```
P   s1  1+,2+,3+,4+,5+,6+,7+,8+ 0M,0M,0M,0M,0M,0M,0M
P   s2  1+,2+,6+,7+,8+  0M,0M,0M,0M
P   s3  4+,5+,6+,7+,9+,2+,3+,4+,5+,6+,7+,10+,2+,6+  0M,0M,0M,0M,0M,0M,0M,0M,0M,0M,0M,0M,0M
```

When we subset on segments 6 or 7 we should just parse each s1,s2,s3 and decide what info they provide to the new subgraph. In the case of s1 and s2 this simply becomes

```
P   s1 6+,7+ 0M
P   s2 6+,7+  0M
```

Whereas for s3 we should really create two new paths, since the information that 7 is connected to 6 through an intermediate path is lost.

```
P  s4 6+,7+ 0M
P  s5 6+,7+ 0M
```

This means that when we are subsetting we would need to keep track of when segments are repeated. This is easier in a single line format because we know right there that we have all the data we are ever going to get. Multiline means you would need to keep track of the state of the path parsing for each possible path.

I agree with the sentiment that parsing should be as easy as possible. Ideally this should not require anything more than `readline` and `split`

btw I'm working on a simple python parser for GFA, [pmelsted/pyGFA](https://github.com/pmelsted/pyGFA) meant to validate the spec and see if we are missing anything (not a reference impl like cPython). I plan on doing the subgraph operation soon.

**Comment by pmelsted** [comment]
And apparently I'm not staying on topic, but let's get back to circular paths.

I agree that handling circular paths at the cigar level is fine. I would like to add one more example to think about

```
H   VN:Z:1.0
S   1   AGCGTA
S   2   TAACAG
S   3   GTCATC
L   1   +   2   +   2M
L   2   +   3   +   2M
L   3   +   1   +   2M
P   linear_path 1+,2+,3+    *,*
P   circular_path   1+,2+,3+    *,*,*
P   more_than_circular 1+,2+,3+,1+ *,*,0M
P   is_this_okay   1+,2+,3+    *
```
In this case the `more_than_circular` implies that we have a fragment where the sequence is something like `AGCGTA-ACAG-CATC-AGCGTA`, i.e. segment 1 is observed twice (I've put in dashes to indicate where the links are). This is not the same as `circular_path` where we observe that 1,2,3 are aranged in a cycle.

**Comment by ekg** [comment]
Is the preferred way of indicating if a path is circular to add:

```
Z:FL:circular
```

... to the path line?

**Comment by sjackman** [comment]
@jmarshall wrote in https://github.com/GFA-spec/GFA-spec/issues/89#issuecomment-495187720…
> FYI SAM has recently settled on `TP:circular` (“topology”; see samtools/hts-specs#403).

**Comment by sjackman** [comment]
GFA will adopt this same `TP:Z:circular` option.

**Comment by ekg** [comment]
For completeness, we should allow `TP:Z:linear` as well.
