### ISSUE TITLE
[GFA1] Regexp for Path overlaps

### ISSUE THREAD

**Issue by ggonnella** [GFA-spec/GFA-spec#45]
Still with the intention of finalizing the GFA 1.0 specification, before moving to GFA 2.0, I noticed that the Regexp for Overlaps in the P lines is incomplete, as it codes only single CIGARs and not the entire content of the field, as it is the case of all other Regexps in the specification. Either we write this in the text or, better, we fix the Regexp.

If I get it right, valid values are a single *, muliple comma-separated \* or CIGARS, and also comma-separated combinations of \* and CIGARS (necessary e.g if some of the underlying links have a \* overlap and some have a CIGAR). 

I have written a Pull Request #46 in which I fix this, but please double check the combined regexp again.

**Comment by sjackman** [comment]
SegmentNames needs commas as well.

**Comment by sjackman** [comment]
I find the regex rather unwieldy though. I'm inclined to remove them, and perhaps just describe them in plain text. Thoughts? @ggonnella @lh3

**Comment by ggonnella** [comment]
Also the regex for B-types arrays is not really correct, as it does consider that floats are only valid if there is an f as subtype specifier

The correct one should be:
```(f(,[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)+|[csi](,\+?[0-9]+)+|[CSI](,[-+]?[0-9]+)+)```

**Comment by jmarshall** [comment]
Re B arrays, note that `[csi]` are signed and `[CSI]` are unsigned, so the `\+?` and `[-+]?` should be the other way around.  I guess a similar `f|[csi]|[CSI]`-style RE would be more accurate in the SAM spec too, but I'm not sure that this is making the RE any more comprehensible!

To the extent that these optional fields are modelled on SAM optional fields, you might want to consider also the bug fixes that we've made in samtools/hts-specs#135.

In particular (see PR samtools/hts-specs#155), `*` instead of `+` in the **Z** and **H** types allows for zero-length strings, and **H** needs to be an even number of hex digits.  And similarly **B** should probably allow for zero-length arrays to be valid, though this is still under discussion in the hts-specs issue.
